#! /usr/bin/perl

# Unfinished program to create an partial result. The round
# is harcoded in here, and you need to give the e-mail of
# the players on stdin.

# This is useful fo generate TOU file of players that didn't
# finish their games in time.


# TODO: document and maek a proper interface.

use Tournament;
use strict;

my $t = Tournament->load("toperm");

sub my_time {
    return time;
}

my @players;
while (<>) {
    push @players, $t->find_player_by_email($_);
}

my @rounds = @{$t->Round}[4];

print $t->tou_header;
print $t->tou_results(\@players, \@rounds);
