#! /usr/bin/perl -w

# Goat: Gentil Organisateur et Administrateur de Tournois
# Copyright (C) 2006-2018  Yves Rutschle
# 
# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later
# version.
# 
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more
# details.
# 
# The full text for the General Public License is here:
# http://www.gnu.org/licenses/gpl.html

=head1 NAME

 update_field - manually update player fields in a tournament file

=head1 SYNOPSIS

 update_field [-n|--no-act] [-f file] --select <email>  
        [--email <new_email>]
        [--license <license>]
        [--level <level>]

=head1 DESCRIPTION

Selects a user by email; changes its email address

=cut

use strict;
use locale;
use Getopt::Long;
use Pod::Usage;

use Data::Dumper;

use Tournament;
use GoatConfig;

my ($no_act, $help, $out_email, $in_email,
    $in_level,
    $in_license);
GetOptions(
    'help' => \$help,
    'n' => \$no_act,
    'no-act' => \$no_act,
    'email=s' => \$out_email,
    'license=s' => \$in_license,
    'level=s' => \$in_level,
    'select=s' => \$in_email,
) or die pod2usage();

die pod2usage(-verbose=>2) if defined $help;
die "No player email specified. Use -select <email>.\n" unless defined $in_email;

my $tournament = load Tournament $TOURNAMENT_FILE;



my $player = $tournament->find_player_by_email($in_email);
die "No player found\n" unless defined $player;

$player->email($out_email) if defined $out_email;
$player->license($in_license) if defined $in_license;
$player->level($in_level) if defined $in_level;

$tournament->save($TOURNAMENT_FILE) unless $no_act;

