#! /usr/bin/perl -w

# Anonymise e-mail addresses of a file by replacing the
# domain with example.tld. This is to avoid using real
# addresses in test files that are published.

use strict;

my $tournament_fn = shift @ARGV;

my $f;
open $f, $tournament_fn;
while (<$f>) {
    s/\@.*\b/\@example.com/;
    print;
}


