#! /usr/bin/perl -w

# Anonymise e-mail addresses of a tournament file by
# replacing the domain with example.tld. This is to avoid
# using real addresses in test files that are published. The
# other data (name, license and whatnot) are public anyway.

use strict;
use Tournament; # this complains about not finding the conf, but whatever

my $tournament_fn = shift @ARGV;

open my $f, $tournament_fn;
while (<$f>) {
    s/\@.*/\@example.com/;
    print;
}


